### ISSUE TITLE
CSS Variables not supported in media queries for breakpoint tokens

### ISSUE THREAD

**Issue by josh-bagwell** [Workday/canvas-tokens#121]
### Expected Behavior

Breakpoint tokens currently do not work as intended. 

This is due to css variables not being supported inside of media queries currently. 

The below will not work:
```tsx
[`@media screen and (max-width: ${cssVar(system.breakpoints.m)})`]: {}
```
But this will:
```tsx
[`@media screen and (max-width: 48rem)`]: {}
```

### Actual Behavior

What ends up happening is the value for the breakpoint is not used since css variables are not supported by media queries.

**Comment by RayRedGoose** [comment]
Value should be in px

**Comment by RayRedGoose** [comment]
close with #124
