### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-tokens#13]
## 💡 Suggestion

We need to make a handful of developer-focused improvements to make canvas-tokens-web easier to use.

- [ ] Move CSS, SCSS, and LESS directories out of `dist`.
  - This will allow devs to import CSS from `@workday/canvas-tokens-web/css/_variables.css` instead of `/dist`.
- [x] #41
  - This will improve intellisense and typeahead support.
- [ ] Add JSDoc to describe token values. E.g. `2rem (32px)` for `space.x8`.
  -  This will improve intellisense and typeahead support.

### Motivation

Helping developers transition to the new tokens will reduce frustration.

**Comment by josh-bagwell** [comment]
Discussion on using `system.shape.circle` on `borderRadius`. In practice, it may be a bit confusing using something called `shape` and have it be `medium`.
