### ISSUE TITLE
Add missing color tokens

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-tokens#99]
## 🚀 Feature Proposal

- Update system.color.bg.muted.soft (licorice.200)
- Add system.color.bg.muted.softer (licorice.100)
- Add system.color.bg.alt.softer (soap.100)
- Add system.color.border.input.inverse (soap.300)
- Add system.color.fg.muted.soft (licorice.200)
- Add system.color.static.gold.stronger (toastedMarshmallow.600)
- Add system.color.text.primary.stronger (blueberry.600)

**Comment by RayRedGoose** [comment]
Done with #98
